[general]
import = [
    "~/.config/alacritty/alacritty-common.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[window]
opacity = 0.85
startup_mode = "Maximized"

[terminal.shell]
program = "/usr/bin/zsh"
