[general]
import = [
   "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
]

### keep
# Afterglow.toml
# Alabaster_dark.toml
# Base16_default_dark.toml
# Blood_moon.toml
# Breeze.toml
# Xterm.toml"
# Hyper.toml"
# citylights.toml
# campbell.toml

[cursor.style]
blinking = "Always"

[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Mono"

[keyboard]
bindings = [
    # tmux refresh
    { key = "L", mods = "Control", chars = "\u0001V" },
    # tmux west pane
    { key= "H", mods= "Command", chars= "\u0001h" },
    # tmux south pane
    { key= "J", mods= "Command", chars= "\u0001j" },
    # tmux north pane
    { key= "K", mods= "Command", chars= "\u0001k" },
    # tmux east pane
    { key= "L", mods= "Command", chars= "\u0001l" },
    { key= "H", mods= "Command|Shift", chars= "\u0001\u0008" },
    { key= "J", mods= "Command|Shift", chars= "\u0001\u000a" },
    { key= "K", mods= "Command|Shift", chars= "\u0001\u000b" },
    { key= "L", mods= "Command|Shift", chars= "\u0001\u000c" },
    { key= "F", mods= "Command|Shift", chars= "\u0001\u007a" },
    { key= "H", mods= "Command|Alt", chars= "\u0001O" },
    { key= "J", mods= "Command|Alt", chars= "\u0001Q" },
    { key= "K", mods= "Command|Alt", chars= "\u0001R" },
    { key= "L", mods= "Command|Alt", chars= "\u0001P" },
    { key= "Key1", mods= "Command", chars= "\u0001A" },
    { key= "Key2", mods= "Command", chars= "\u0001B" },
    { key= "Key3", mods= "Command", chars= "\u0001C" },
    { key= "Key4", mods= "Command", chars= "\u0001D" },
    { key= "Key5", mods= "Command", chars= "\u0001E" },
    { key= "Key6", mods= "Command", chars= "\u0001F" },
    { key= "Key7", mods= "Command", chars= "\u0001G" },
    { key= "Key8", mods= "Command", chars= "\u0001I" },
    { key= "Key9", mods= "Command", chars= "\u0001M" },
    { key= "Key0", mods= "Command", chars= "\u0001N" },
    { key= "D", mods= "Command", chars= "\u0001%" },
    { key= "D", mods= "Command|Shift", chars= "\u0001\"" },
    { key= "W", mods= "Command", chars= "\u0001," },
    { key= "Q", mods= "Alt", chars= "\u0001q" },
    { key= "Q", mods= "Control", chars= "\u0001q" },
    { key= "M", mods= "Command", chars= "\u0001T" },
    { key= "M", mods= "Shift|Command", chars= "\u0001S" },
    { key= "N", mods= "Shift|Command", chars= "\u0001U" },
    { key= "Space", mods= "Shift", chars= "\u000d" },
]

[window]
opacity = 1.0
startup_mode = "Maximized"
decorations = "None"

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 132
lines = 32
