return {
    settings = {
        pylsp = {
            enabled = true,
            trace = { server = 'verbose' },
            configurationSources = {},
            plugins = {
                pylsp_flake8 = { enabled = true },
                pylsp_pylint = { enabled = false },
                pylsp_pycodestyle = { enabled = false },
                pylsp_pyflakes = { enabled = false },
                pylsp_jedi = { enabled = true },
                pylsp_jedi_completion = { enabled = true },
                pylsp_jedi_definition = { enabled = true },
                pylsp_jedi_hover = { enabled = true },
                pylsp_mccabe = { enabled = true },
                pylsp_preload = { enabled = false },
                pylsp_pydocstyle = { enabled = false },
                pylsp_rope_completion = { enabled = false },
                pylsp_yapf = { enabled = false },
                pylsp_rope = { enabled = false },
                -- 3rd parties
                pylsp_mypy = { enabled = true },
                black = { enabled = false },
                isort = { enabled = false },
                -- deprecated api call
                memestra = { enabled = false },
            },
            --			plugins = {
            --				flake8 = {
            --					config = "",
            --					enabled = false,
            --					exclude = {},
            --					executable = "",
            --					filename = "",
            --					hangClosing = false,
            --					ignore = {},
            --					maxLineLength = 0,
            --					perFileIgnores = {},
            --					select = {},
            --				},
            --				jedi = {
            --					extra_paths = {},
            --					env_vars = {},
            --					environment = "",
            --				},
            --				jedi_completion = {
            --					enabled = true,
            --					include_params = true,
            --					include_class_objects = true,
            --					fuzzy = true,
            --					eager = false,
            --					resolve_at_most_labels = 25,
            --					cache_labels_for = { "actors" },
            --				},
            --				jedi_definition = {
            --					enabled = true,
            --					follow_imports = true,
            --					follow_builtin_imports = true,
            --				},
            --				jedi_hover = { enabled = true },
            --				jedi_references = { enabled = true },
            --				jedi_signature_help = { enabled = true },
            --				jedi_symbols = {
            --					enabled = true,
            --					all_scopes = false,
            --					include_import_symbols = true,
            --				},
            --				mccabe = {
            --					enabled = false,
            --					threshold = 15,
            --				},
            --				preload = {
            --					enabled = false,
            --					modules = {},
            --				},
            --				pycodestyle = {
            --					enabled = false,
            --					exclude = {},
            --					filename = {},
            --					select = {},
            --					ignore = {},
            --					hangClosing = false,
            --					maxLineLength = 0,
            --				},
            --				pydocstyle = {
            --					enabled = false,
            --					convention = "",
            --					addIgnore = {},
            --					addSelect = {},
            --					ignore = {},
            --					select = {},
            --					match = "",
            --					matchDir = "",
            --				},
            --				pyflakes = { enabled = false },
            --				pylint = {
            --					enabled = false,
            --					args = {},
            --					executable = "",
            --				},
            --				rope_completion = {
            --					enabled = false,
            --					eager = false,
            --				},
            --				yapf = {
            --					enabled = false,
            --				},
            --				rope = {
            --					extensionModules = "",
            --					ropeFolder = {},
            --				},
            --				mypy = { enabled = false },
            --			},
        },
    },
}
