session_name: environment
start_directory: $WORKSPACE
environment:
  PROJECT_NAME: environment
  WORKSPACE: $WORKSPACE

plugins:
  - tmuxp_plugin_loader.plugin.Loader

windows:

  - window_name: device-specific
    layout: even-horizontal
    panes:
      - shell_command:
        - editor "$DOTFILES/env/.env-$(uname -n)"
        focus: true
      - shell_command:
        - editor "$DOTFILES/env/requirements-$(uname -n).txt"

  - window_name: zshrc
    start_directory: $DOTFILES/zsh
    layout: even-horizontal
    panes:
      - shell_command:
        - editor zshenv
        focus: true
      - shell_command:
        - editor .zshrc
