session_name: $PROJECT_NAME
start_directory: $WORKSPACE
environment:
  WORKSPACE: $WORKSPACE
  PROJECT_NAME: $PROJECT_NAME

plugins:
  - tmuxp_plugin_loader.plugin.Loader

windows:

  - window_name: global
    start_directory: .
    panes:
      - shell_command:
          - $EDITOR .

  - window_name: neovim
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
          - $EDITOR ./nvim/.

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
          - cd ./zsh && $EDITOR .
        focus: true
      - shell_command:
          - cd ./bin && $EDITOR .

  - window_name: tmux
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
          - cd ./tmux && $EDITOR tmux.conf
        focus: true
      - shell_command:
          - cd $TMUXP_CONFIGDIR/templates && $EDITOR $TMUX_TEMPLATE

  - window_name: alacritty
    start_directory: ./alacritty
    layout: even-horizontal
    panes:
      - shell_command:
          - $EDITOR .

  # - window_name: i3
  #   start_directory: ./i3
  #   layout: even-horizontal
  #   panes:
  #     - shell_command:
  #         - $EDITOR .

  - window_name: sway
    start_directory: ./sway
    layout: even-horizontal
    panes:
      - shell_command:
          - $EDITOR .
