session_name: "keybinds"
start_directory: $WORKSPACE 
environment:
  PROJECT_NAME: "keybinds"
  WORKSPACE: $WORKSPACE

windows:

  - window_name: neovim
    start_directory: $DOTFILES/nvim/lua/av
    panes:
      - shell_command:
        - editor ./keymaps.lua

  - window_name: zsh
    start_directory: $DOTFILES/zsh
    panes:
      - shell_command:
        - editor ./keybinds

  - window_name: tmux
    start_directory: $DOTFILES/tmux
    panes:
      - shell_command:
        - editor ./tmux.conf

  - window_name: alacritty
    start_directory: $DOTFILES/alacritty
    panes:
      - shell_command:
        - editor ./keymaps.yml

  - window_name: kitty
    start_directory: $DOTFILES/kitty
    panes:
      - shell_command:
        - editor ./kitty.conf
