session_name: "keybinds"
start_directory: $WORKSPACE 
environment:
  PROJECT_NAME: "keybinds"
  WORKSPACE: $WORKSPACE

plugins:
  - tmuxp_plugin_loader.plugin.Loader

windows:

  - window_name: neovim
    start_directory: $DOTFILES/nvim/lua/av
    panes:
      - shell_command:
        - $EDITOR ./keymaps.lua

  - window_name: zsh
    start_directory: $DOTFILES/zsh
    layout: even-horizontal
    panes:
      - shell_command:
        - $EDITOR ./keybinds
        focus: true
      - shell_command:
        - $EDITOR ./aliases

  - window_name: tmux
    start_directory: $DOTFILES/tmux
    panes:
      - shell_command:
        - $EDITOR ./tmux.conf

  - window_name: alacritty
    start_directory: $DOTFILES/alacritty
    panes:
      - shell_command:
        - $EDITOR ./keymaps.yml
