#!/bin/sh

source $ZALIASES/zsh-aliases

alias ls='ls -G'
alias ns='netstat -p tcp nltu'
alias ncdu='ncdu --exclude=/Users/yul/.av-mp'


# Wine Executables
alias vgmtrans='wine ${WINEDIR}/vgmtrans/bin/vgmtrans.exe'
alias spctool='wine ${WINEDIR}/SPCTool/SPCTool.exe'
alias tagscanner='wine ${WINEDIR}/tagscan-6/Tagscan.exe'
alias glow='wine ${WINEDIR}/Glow/Glow.exe'
alias spcplay='wine ${WINEDIR}/spcplay-2.18.1.6862/spcplay.exe'
alias foobar='wine ${WINEDIR}/Program\ Files\ \(x86\)/foobar2000/foobar2000.exe'
alias looping='wine ${WINEDIR}/Looping32.exe'

# Divers
alias insta='python3 ~/Desktop/Network/thot_bot/minimal_api/minimal_scraper.py'

alias esptool='python3 -m esptool --port ${MCU}'
alias rshell='rshell --port ${MCU} --baud 115200'
alias mpy='~/./bin/micropython'
alias makempy='make CROSS=x86_64-linux-musl-'

alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

alias lua-language-server="$HOME/bin/lua-language-server/bin/lua-language-server" "$@"

alias nvim="$NEOVIM_OPTS $NEOVIM_BIN"

alias av='python3 $DEV/Network/mplayer_old/mplayer.py'
alias flX="pushd $DEV/Network/mplayer && source .envrc && exe && popd"
