#!/bin/sh

alias ll='ls -lh'
alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='LC_ALL=C  grep --color=auto'
#alias grep='LC_ALL=C  grep --color=auto --exclude-dir={.av-mp}'
# confirm before overwriting something
# alias cp="cp -i"
# alias mv='mv -i'
# alias rm='rm -i'

alias df='df -h'     # human-readable sizes
# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

alias kubectl="minikube kubectl --"

alias cfg="pushd $DOTCONF && nvim -c NvimTreeToggle && popd"

alias tn="tmux -u -f $DOTCONF/tmux/.tmux.conf new"
alias ta="tmux -u -f $DOTCONF/tmux/.tmux.conf attach"
alias tc="nvim $DOTCONF/tmux/.tmux.conf"
