#!/bin/sh

source $ZALIASES/zsh-aliases

alias ls='ls -G'
alias av='python3 $DEV/Network/mplayer_old/mplayer.py'

# docker
# alias up='docker compose up --build'
# alias down='docker compose down'
alias run='docker compose run'
#alias exe='docker exec -it'


# Wine Executables
alias vgmtrans='wine ${WINEDIR}/vgmtrans/bin/vgmtrans.exe'
alias spctool='wine ${WINEDIR}/SPCTool/SPCTool.exe'
alias tagscanner='wine ${WINEDIR}/tagscan-6/Tagscan.exe'
alias glow='wine ${WINEDIR}/Glow/Glow.exe'
alias spcplay='wine ${WINEDIR}/spcplay-2.18.1.6862/spcplay.exe'
alias foobar='wine ${WINEDIR}/Program\ Files\ \(x86\)/foobar2000/foobar2000.exe'
alias looping='wine ${WINEDIR}/Looping32.exe'

# Divers
alias insta='python3 ~/Desktop/Network/thot_bot/minimal_api/minimal_scraper.py'

alias esptool='python3 -m esptool --port ${MCU}'
alias rshell='rshell --port ${MCU} --baud 115200'
alias mpy='~/./bin/micropython'
alias makempy='make CROSS=x86_64-linux-musl-'

alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

alias ns='netstat -p tcp nltu'
alias ncdu='ncdu --exclude=/Users/yul/.av-mp'

alias lua-language-server="$HOME/bin/lua-language-server/bin/lua-language-server" "$@"

alias nvim="XDG_CONFIG_HOME=${DOTCONF} XDG_DATA_HOME=${HOME}/.local/share XDG_CACHE_HOME=${HOME}/.cache PATH=/opt/local/libexec/llvm-14/bin:${HOME}/bin/lua-language-server/bin:${PATH} nvim"

alias flX="pushd $DEV/Network/mplayer && source .envrc && exe && popd"
alias COMPOSE_CMD='docker compose'
