#!/bin/sh

source $ZALIASES/zsh-aliases

alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias ns='netstat -plntu'
alias ls='ls --color=auto'

# docker
# alias up='docker-compose up --build'
# alias down='docker-compose down'
alias run='docker-compose run'

alias nvim="XDG_CONFIG_HOME=$DOTCONF XDG_DATA_HOME=$HOME/.local/share XDG_CACHE_HOME=$HOME/.cache PATH=$HOME/bin/lua-language-server:$PATH nvim"

alias clangd='clangd-15'

