services:
  app:
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}:${PROJECT_VERSION}
    build:
      context: .
    network_mode: host
    environment:
      PROJECT_NAME: $PROJECT_NAME
      PROJECT_VERSION: $PROJECT_VERSION
