require('av.set')
require('av.keymaps')
require('av.packer')

require('av.cmp')
require('av.lsp')
require('av.telescope')
require('av.tree-sitter')
-- require('av.gitsigns')
require('av.harpoon')
-- require('av.obsidian')
require('av.ui')
