#!/bin/sh

source $ZFUNCTIONS/zsh-functions

f() { find -E $1 -regex ".*\.($2)" -print0 | xargs -0 grep -n -d skip $3 }
#f() { find -E $1 -regex ".*\.($2)" -print0 | xargs -0 grep -n $3 }
fe() { find -E $1 -regex ".*\.($2)" }

# adb_connect() { adb connect "${IPADDR}:5555" }

avgen() { python3 ${ENV}/avgen.py $PWD $1 }
github() { python3 ${ENV}/github.py }

upgrade() {
    ### Macports
    sudo port selfupdate;
    sudo port upgrade outdated;
    ### ZSH plugins
    find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q;
    ### Homebrew
    brew upgrade;
    ### PIP, Python3 global packages
    python3 -m pip install --upgrade pip;
    python3 -m pip uninstall -y -r <(python3 -m pip freeze --user);
    python3 -m pip install -r $DOTCONF/requirements.txt;
    ### NPM, Node global packages
    sudo npm install -g npm@latest;
    sudo npm update -g;
    ### Pull updates from github
    python3 ${ENV}/github.py;
    ### Rust crates
    LIBSSH2_SYS_USE_PKG_CONFIG=whatever cargo install-update --all;
}

cleanup() {
    sudo port uninstall leaves;
    brew autoremove;
    brew cleanup --prune=all;
    sudo rm -rf $(brew --cache)
    sudo port -f clean --all all;
    python3 -m pip cache purge;
    cargo cache clean-unref;
    cargo cache --autoclean;
    npm cache clean --force;
}

ig-scraper() { $SCRIPTDIR/instagram/venv/bin/python $SCRIPTDIR/instagram/main.py $1 }
exe() { eval $EXE }
