#!/bin/sh

source $ZFUNCTIONS/zsh-functions

f() { find -E $1 -regex ".*\.($2)" -print0 | xargs -0 grep -n $3 }

function upgrade() {
    _upgrade;
    # APT
    sudo apt update && sudo apt upgrade -y;
 }

function _upgrade_nvim() {
    git clone --depth 1 https://github.com/neovim/neovim ~/neovim;
    cd ~/neovim && make CMAKE_BUILD_TYPE=Release;
    sudo make install;
    cd .. && sudo rm -rf neovim;
}

function _upgrade_lua() {
    git clone  --depth 1 https://github.com/sumneko/lua-language-server ~/lua-language-server;
    cd lua-language-server && git submodule update --depth 1 --init --recursive;
    cd 3rd/luamake && ./compile/install.sh;
    cd ../.. && ./3rd/luamake/luamake rebuild;
    rm -rf ~/bin/lua-language-server;
    cp -rf bin ~/bin/lua-language-server;
    cd .. && rm -rf lua-language-server;
}
