#!/bin/sh

source $ZFUNCTIONS/zsh-functions

f() { find -E $1 -regex ".*\.($2)" -print0 | xargs -0 grep -n -d skip $3 }
#f() { find -E $1 -regex ".*\.($2)" -print0 | xargs -0 grep -n $3 }
fe() { find -E $1 -regex ".*\.($2)" }

# adb_connect() { adb connect "${IPADDR}:5555" }

avgen() { python3 ${ENV}/avgen.py $PWD $1 }

github() { 
    pushd $ENV/github;
    GITHUB_REPOS=$GITHUB_REPOS python github.py;
    popd;
}

upgrade() {
    _upgrade;
    ### Macports
    sudo port selfupdate;
    sudo port upgrade outdated;
    ### Homebrew
    brew upgrade;
    ### NPM, Node global packages
    sudo npm install -g npm@latest;
    sudo npm update -g;
    ### Pull updates from github
    python3 ${ENV}/github.py;
    ### Rust crates
    LIBSSH2_SYS_USE_PKG_CONFIG=whatever cargo install-update --all;
    ### Neovim
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync';
}

cleanup() {
    ### Macports -- slow
    echo "cleaning MacPorts cache"
    sudo port uninstall leaves;
    sudo port -f clean --all all;
    ### Homebrew
    echo "cleaning Homebrew cache"
    brew autoremove;
    brew cleanup --prune=all;
    ### Python
    echo "cleaning pip cache"
    python3 -m pip cache purge;
    ### Rust
    echo "cleaning cargo cache"
    cargo cache clean-unref;
    cargo cache --autoclean;
    ### JS/TS
    echo "cleaning npm cache"
    sudo npm prune;
    sudo npm cache clean --force;
    ### App cache
    echo "removing user app-cache"
    sudo rm -rf $HOME/Library/Caches/*;
    sudo rm -rf $HOME/.cache/*;
    ### Misc
    echo "removing misc artifacts"
    rm -rf $HOME/node_modules;
}

ig-scraper() { $SCRIPTDIR/instagram/venv/bin/python $SCRIPTDIR/instagram/main.py $1 }
exe() { eval $EXE }
