return {
  {
    "mason-org/mason.nvim",
    opts = {}
  },
  'nvimtools/none-ls.nvim',
  'ledger/vim-ledger',
  -- 'windwp/nvim-autopairs',
  'tpope/vim-commentary',
  { 'numToStr/Comment.nvim', opts = {} },
  { 'vague2k/vague.nvim' },
  require('plugins.telescope'),
  require('plugins.treesitter'),
  -- require('plugins.treesitter-context'),
  require('plugins.gitsigns'),
  require('plugins.undotree'),
  require('plugins.lualine'),
  require('plugins.gruvbox-baby'),
  require('plugins.indent-blankline'),
  require('plugins.oil'),
  require('plugins.harpoon'),
  require('plugins.illuminate'),
  require('plugins.nvim-colorizer'),
  require('plugins.luasnip'),
  require('plugins.trouble'),
}
