#!/bin/sh

. "$ZDOTDIR/aliases"

alias ls='ls --color=auto'

alias cb-copy='xclip -selection clipboard'
alias cb-paste='xclip -selection clipboard -o'

alias d='/usr/local/bin/docker'

if command -v ss 1>/dev/null; then
	alias ns='ss --listening --processes --info --summary --ipv4 --tcp'
elif command -v netstat 1>/dev/null; then
	alias ns='netstat -plntu'
else
	alias ns='lsof -i -P -n'
fi
alias s='/usr/bin/systemctl'
alias lock='i3lock -c 000000'

alias g='/usr/bin/git'
alias sudo='sudo '
alias tg='tag-reader '

alias j='/bin/journalctl '
alias ju='/bin/journalctl -xeu '
alias jr='/bin/journalctl --flush --rotate --vacuum-time=1s && /bin/journalctl --user --flush --rotate --vacuum-time=1s'

alias s='/bin/systemctl '
alias sr='/bin/systemctl restart '
alias so='/bin/systemctl stop '
alias sa='/bin/systemctl start '
alias ss='/bin/systemctl status '
alias sdr='/bin/systemctl daemon-reload '
