#!/bin/sh

alias ll='ls -lh'
alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='LC_ALL=C  grep --color=auto'
#alias grep='LC_ALL=C  grep --color=auto --exclude-dir={.av-mp}'

alias df='df -h'     # human-readable sizes
# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

alias kubectl="minikube kubectl --"

alias tn="tmux -u new"
alias ta="tmux -u attach"

alias tx="tmuxp"
alias txi="tmuxp import tmuxinator"

cfg() {
    if ! test -z "$TMUX"; then
        editor "$DOTCONF"
    else
        tmuxp-start "$DOTCONF"
    fi
}

v() { editor "$@"; }
