#!/bin/sh

. "$ZDOTDIR/aliases"

alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias ns='netstat -plntu'
alias ls='ls --color=auto'
