#!/bin/sh

. "$ZDOTDIR/aliases"

alias ls='ls -G'
alias ns='netstat -p tcp nltu'
alias ns="netstat -anvp tcp | awk 'NR<3 || /LISTEN/'"
alias ncdu='ncdu --exclude=~/.av-mp'

# Wine Executables
alias vgmtrans='wine ${WINEDIR}/vgmtrans/bin/vgmtrans.exe'
alias spctool='wine ${WINEDIR}/SPCTool/SPCTool.exe'
alias tagscanner='wine ${WINEDIR}/tagscan-6/Tagscan.exe'
alias glow='wine ${WINEDIR}/Glow/Glow.exe'
alias spcplay='wine ${WINEDIR}/spcplay-2.18.1.6862/spcplay.exe'
alias foobar='wine ${WINEDIR}/Program\ Files\ \(x86\)/foobar2000/foobar2000.exe'
alias looping='wine ${WINEDIR}/Looping32.exe'

# Divers
alias insta='python3 ~/Desktop/Network/thot_bot/minimal_api/minimal_scraper.py'

alias esptool='python3 -m esptool --port ${MCU}'
alias rshell='rshell --port ${MCU} --baud 115200'
alias mpy='~/./bin/micropython'
alias makempy='make CROSS=x86_64-linux-musl-'

alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

alias av='python3 $DEV/Network/mplayer_old/mplayer.py'
flX() {
    TMUX_TEMPLATE=".tmuxp-1.yaml" tmuxp-start "$DEV/Network/mplayer"
}
clear() {
  if [ -n "$TMUX" ]; then
    tmux clear-history
  fi
  /opt/local/bin/clear
}
