#!/bin/sh

if ! command -v fd 1>/dev/null; then
	fd() {
		/usr/bin/find . -iname "*${1}*"
	}
	alias fdi="fd"
else
	alias fdi="fd --no-ignore-vcs --no-ignore-parent --hidden"
fi

if command -v rg 1>/dev/null; then
	alias rgi="rg --no-ignore-vcs --no-ignore-parent --hidden --ignore-case"
else
	alias rgi="grep -rn"
fi

v() {
	env $EDITOR "$*"
}

jw() {
	[ -d "$WORKSPACE" ] && cd "$WORKSPACE" || return 1
}

dt() {
	python3 -c 'import datetime;import sys; sys.stdout.write(str(datetime.datetime.fromtimestamp(int(sys.argv[1]))))' $@
}

alias ls='ls --color=auto'
alias grep='LC_ALL=C  grep --color=auto'
alias ll='ls -lh'
alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
