#!/bin/sh

. "$ZDOTDIR/aliases"

alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias ls='ls --color=auto'

alias cb-copy='xclip -selection clipboard'
alias cb-paste='xclip -selection clipboard -o'

alias d='/usr/local/bin/docker'

if command -v ss 1>/dev/null; then
	alias ns='ss --listening --processes --info --summary --ipv4 --tcp'
elif command -v netstat 1>/dev/null; then
	alias ns='netstat -plntu'
else
	alias ns='lsof -i -P -n'
fi
alias s='/usr/bin/systemctl'
alias lock='i3lock -c 000000'

# alias g='/usr/bin/git'
alias g="$(go env GOPATH)/bin/gonext"
alias sudo='sudo '
alias tg='tag-reader'
