#!/bin/sh

zle -N history-substring-search-up
zle -N history-substring-search-down
zle -N edit-command-line
zle -N custom-edit-command-line
zle -N my-backward-delete-word
zle -N exit-zero

# push-line
bindkey -r "^Q"
bindkey -r "^[Q"
bindkey -r "^[q"
bindkey -r "^R"
bindkey -r "^S"

bindkey -v "^K" exit-zero
bindkey "^W" my-backward-delete-word

if [ -z "$TMUX" ]; then
	bindkey -v -s "^F" "tmuxp-start\n"
	bindkey -v -s "^G" "tmuxp-debug\n"
	bindkey -v -s "^O" "tmuxp-start $TMUXP_CONFIGDIR/anonymous\n"
	bindkey -v -s "^S" "tmux-attach\n"

	bindkey -v -s "^AA" "tmuxp-start $TMUXP_QUICK1\n"
	bindkey -v -s "^AB" "tmuxp-start $TMUXP_QUICK2\n"
	bindkey -v -s "^AC" "tmuxp-start $TMUXP_QUICK3\n"
	bindkey -v -s "^AD" "tmuxp-start $TMUXP_QUICK4\n"
	bindkey -v -s "^AE" "tmuxp-start $TMUXP_QUICK5\n"
fi

bindkey "^[[5~" beginning-of-line
bindkey "^[[6~" end-of-line
bindkey "^[[3~" delete-char
bindkey "˚" history-substring-search-up
bindkey "∆" history-substring-search-down
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

bindkey "¬" forward-word
bindkey "˙" backward-word
# bindkey "^[[1;3C" forward-word
# bindkey "^[[1;3D" backward-word
bindkey -v "^E" custom-edit-command-line
# bindkey -v "^E" edit-command-line

bindkey -v "^ " autosuggest-accept

if command -v fzf 1>/dev/null; then
	bindkey -v "^H" fzf-history-widget
	bindkey "ƒ" fzf-cd-widget
fi

bindkey -v -s "^R" "run\n"
bindkey -v -s "^B" "build\n"
bindkey -v -s "^U" "up\n"

# Vi mode
bindkey -v
export KEYTIMEOUT=1
bindkey "^?" backward-delete-char
