#!/bin/sh

zle -N history-substring-search-up
zle -N history-substring-search-down
zle -N edit-command-line
zle -N my-backward-delete-word
zle -N exit-zero

# push-line
bindkey -r "^Q" 
bindkey -r "^[Q"
bindkey -r "^[q"
bindkey -r "^R"
bindkey -r "^S"

# bindkey -s "^K" "exit\n"
bindkey "^K" exit-zero
bindkey "^W" my-backward-delete-word

#if [ -z "$TMUX" ] && [ -z "$SSH_CLIENT" ]; then
#  bindkey -s "^F" "tmuxp-start\n"
#  bindkey -s "^N" "tmuxp-edit\n"
#  bindkey -s "^G" "tmuxp-debug\n"
#  bindkey -s "^O" "tmuxp-start $TMUXP_CONFIGDIR/anonymous\n"
#  bindkey -s "^S" "tmux-attach\n"
#else
#  bindkey -s "^F" "vanilla-start\n"
#fi

if [ -z "$TMUX" ]; then
  bindkey -s "^F" "tmuxp-start\n"
  bindkey -s "^N" "tmuxp-edit\n"
  bindkey -s "^G" "tmuxp-debug\n"
  bindkey -s "^O" "tmuxp-start $TMUXP_CONFIGDIR/anonymous\n"
  bindkey -s "^S" "tmux-attach\n"
else
  bindkey -s "^F" "vanilla-start\n"
fi

bindkey "^[[5~" beginning-of-line
bindkey "^[[6~" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^E" edit-command-line
bindkey "^ " autosuggest-accept

if command -v fzf 1> /dev/null; then
  zle -N fzf-path
  bindkey "^X" fzf-path
  bindkey "^H" fzf-history-widget
fi

bindkey -s "^R" "run\n"
bindkey -s "^B" "build\n"
bindkey -s "^U" "up\n"

bindkey -s 'ƒ' "project-most-frecent\n"
