#!/bin/sh

### Additional environment variables
export NEOVIM="$NEOVIM_OPTS $NEOVIM_BIN"
export PERSONAL_PROJECTS="$DEV $DEV/Network $DEV/zoltron_stack $DOTFILES $ENV $TMUXP_CONFIGDIR"
export WORK_PROJECTS="$RSN $HOME/Desktop/Novall $HOME/Desktop/Novall/Novold"

export TMUXINATOR_CONFIG="${TMUXINATOR_CONFIG:-"~/.config/tmuxinator"}"
