#!/bin/sh

export HISTSIZE=1000000
export SAVEHIST=1000000
export MANWIDTH=999
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

[ -f "$DOTFILES/env/.env" ] && . "$DOTFILES/env/.env"
[ -d "$TOOLZ" ] && prepend-to-path "$TOOLZ/bin" && export MANPATH="$TOOLZ/share/man:$MANPATH"
prepend-to-path "$DOTFILES/bin"

export EDITOR="$DOTFILES/bin/editor" && export VISUAL="$EDITOR" && export MANPAGER="$EDITOR -c 'Man!' -o -"

export TMUX_TEMPLATE=".tmuxp.yaml"
export TMUX_CONFIG="$DOTFILES/tmux/tmux.conf"
export TMUXP_CONFIGDIR="${TMUXP_CONFIGDIR:-"~/.config/tmuxp"}"
export GIT_CONFIG_GLOBAL="$DOTFILES/.gitconfig"

# Setup fzf
prepend-to-path "$GITHUB_REPOS/fzf/bin"
[ -f "$GITHUB_REPOS/fzf/shell/completion.zsh" ] && source "$GITHUB_REPOS/fzf/shell/completion.zsh"
[ -f "$GITHUB_REPOS/fzf/shell/key-bindings.zsh" ] && source "$GITHUB_REPOS/fzf/shell/key-bindings.zsh"

# Setup LUA language-server
append-to-path "$GITHUB_REPOS/lua-language-server/bin"

[ -n "$GOWORK" ] && export WORK_PROJECTS="$WORK_PROJECTS" || export WORK_PROJECTS=
[ -n "$GOLEARN" ] && export LEARNING_PROJECTS="$LEARNING_PROJECTS" || export LEARNING_PROJECTS=
export PROJECTS="$PERSONAL_PROJECTS $WORK_PROJECTS $LEARNING_PROJECTS"
