#!/bin/sh

export MANWIDTH=999

hostname="$(uname -n)"
[ -f "$DOTFILES/env/.env-$hostname" ] && source "$DOTFILES/env/.env-$hostname"
[ -z "$PROJECTS_ROOT" ] && export PROJECTS_ROOT="$HOME"

[ -d "$TOOLZ" ] && prepend-to-path "$TOOLZ/bin" && export MANPATH="$TOOLZ/share/man:$MANPATH"
prepend-to-path "$DOTFILES/bin"
prepend-to-path "$HOME/.local/bin"

append-to-path "/usr/local/go/bin"

# Setup fzf
if [ -n "$FZF" ]; then
	prepend-to-path "$REPODIR/fzf/bin"
	[ -f "$REPODIR/fzf/shell/completion.zsh" ] && source "$REPODIR/fzf/shell/completion.zsh"
	[ -f "$REPODIR/fzf/shell/key-bindings.zsh" ] && source "$REPODIR/fzf/shell/key-bindings.zsh"
fi

export EDITOR=eeditor && export VISUAL=eeditor && export MANPAGER="eeditor -c 'Man!' -o -"

export TMUX_TEMPLATE=".tmuxp.yaml"
export TMUX_CONFIG="$DOTFILES/tmux/tmux.conf"
export TMUXP_CONFIGDIR="${TMUXP_CONFIGDIR:-"~/.config/tmuxp"}"
export GIT_CONFIG_GLOBAL="$DOTFILES/.gitconfig"

[ -n "$GOWORK" ] && export WORK_PROJECTS="$WORK_PROJECTS" || export WORK_PROJECTS=
[ -n "$GOLEARN" ] && export LEARNING_PROJECTS="$LEARNING_PROJECTS" || export LEARNING_PROJECTS=
[ -n "$GOGIT" ] && export GIT_PROJECTS="$REPODIR" || export GIT_PROJECTS=
export PROJECTS="$PERSONAL_PROJECTS $WORK_PROJECTS $LEARNING_PROJECTS $GIT_PROJECTS"
