modmap: 
  - name: Global
    remap:
      KEY_CAPSLOCK:
        held: KEY_CAPSLOCK
        alone: KEY_ESC
        free_hold: true
  - name: Alt <-> Super
    remap:
      KEY_LEFTALT: KEY_LEFTMETA
      KEY_RIGHTALT: KEY_RIGHTMETA
      KEY_LEFTMETA: KEY_LEFTALT
      KEY_RIGHTMETA: KEY_RIGHTALT
    device:
      only: ['AT Translated Set 2']
  - name: Firefox Alt <-> Super
    remap:
      KEY_LEFTALT: KEY_LEFTMETA
      KEY_LEFTMETA: KEY_LEFTALT
    application:
      only:
        firefox

keymap:
  - name: Accute Accent
    remap:
      KEY_RIGHTALT-KEY_E: [KEY_COMPOSE, KEY_APOSTROPHE]
  - name: Grave Accent
    remap:
      KEY_RIGHTALT-KEY_GRAVE: [KEY_COMPOSE, KEY_GRAVE]
  - name: Circumflex Accent
    remap:
      KEY_LEFTALT-KEY_I: [KEY_COMPOSE, KEY_LEFTSHIFT-KEY_6]
  - name: Cedille
    remap:
      KEY_RIGHTALT-KEY_C: [KEY_COMPOSE, KEY_COMMA, KEY_C]
