plugins:
  - tmuxp_plugin_loader.plugin.Loader
options:
  automatic-rename: on
synchronize-panes: on

windows:
  - window_name: editor
    # options:
    #   automatic-rename: on
    #   main-pane-height: 30
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
        - editor .
    # options_after:
    # synchronize-panes: on

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - pane
